# TFC
name: Actions WIF Demo

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  GitHub-Actions-on-GKE:
    runs-on: arc-runner-set-private-cgsyam-ghe-org
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Git repo checkout'
        uses: actions/checkout@v4
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          token_format: 'access_token'
          workload_identity_provider: 'projects/1000025393506/locations/global/workloadIdentityPools/org-wif-prod/providers/gh-provider'
          service_account: 'sa-tfe-appcode-0045-nonprod@prj-appcode-0045-nonprod-2464.iam.gserviceaccount.com'
          
      - name: 'Configure docker login for GAR, GCR'
        run: gcloud auth configure-docker gcr.io,us-central1-docker.pkg.dev
        
      #- name: 'Run packer build'
      #  run: docker run -v $(pwd)/packer:/tmp/packer gcr.io/product-labs-gsd/packer build -var 'image_name=packer-${{ github.run_id }}' -var 'project_id=product-labs-gsd' -var 'image_family=debian-cloud' -var 'image_zone=us-central1-a' -var access_token=${{ steps.auth.outputs.access_token }} -debug /tmp/packer/packer.json
      
      - name: 'Run docker build'
        run: cd docker && docker build -t us-central1-docker.pkg.dev/product-labs-gsd/syamcg-docker/alpine-custom:latest .
      
      - name: 'Run docker push'
        run: docker push us-central1-docker.pkg.dev/product-labs-gsd/syamcg-docker/alpine-custom:latest
      
      - name: 'List objects - prj 1'
        run: gcloud storage ls gs://dataflow-staging-us-central1-1000025393506/staging/template_launches

      - name: 'List objects - prj 2'
        run: gcloud storage ls gs://gcs-cache-ttl-test-456/


      
